# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeKitDemoApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HomeKitDemoApp
  pod ‘CocoaLumberjack’,’~>2.3.0-rc2'
  target 'HomeKitDemoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
